/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.2
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_LEDR */
#define Pin_LEDR_0_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define Pin_LEDR_0_INBUF_ENABLED 0u
#define Pin_LEDR_0_INIT_DRIVESTATE 1u
#define Pin_LEDR_0_INIT_MUXSEL 8u
#define Pin_LEDR_0_INPUT_SYNC 2u
#define Pin_LEDR_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LEDR_0_NUM 7u
#define Pin_LEDR_0_PORT GPIO_PRT13
#define Pin_LEDR_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LEDR_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_LEDR_DRIVEMODE CY_GPIO_DM_OD_DRIVESLOW_IN_OFF
#define Pin_LEDR_INBUF_ENABLED 0u
#define Pin_LEDR_INIT_DRIVESTATE 1u
#define Pin_LEDR_INIT_MUXSEL 8u
#define Pin_LEDR_INPUT_SYNC 2u
#define Pin_LEDR_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_LEDR_NUM 7u
#define Pin_LEDR_PORT GPIO_PRT13
#define Pin_LEDR_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_LEDR_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
